language: julia
codecov: true
os:
  - linux
#   - osx
#   - windows
#   - freebsd
arch:
  - amd64
  - i386
  - arm64
julia:
  - 1
#   - nightly
matrix:
  exclude:
    - os: osx
      arch: i386
    - os: osx
      arch: arm64
    - os: windows
      arch: arm64
    - os: freebsd
      arch: i386
    - os: freebsd
      arch: arm64
jobs:
  allow_failures:
  - julia: nightly
notifications:
  email: false
