authors = ["Chris Coey <coey.chris@gmail.com>"]
name = "Alfonso"
uuid = "b99e6be6-89ff-11e8-14f8-45c827f4f8f2"
version = "0.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
