name = "Hypatia"
uuid = "b99e6be6-89ff-11e8-14f8-45c827f4f8f2"
repo = "https://github.com/chriscoey/Hypatia.jl.git"
version = "0.0.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
GSL = "92c85e6c-cbff-5e0c-80f7-495c94daaecd"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
PolynomialRoots = "3a141323-8675-5d76-9d11-e1df1406c778"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SemialgebraicSets = "8e049039-38e8-557d-ae3a-bc521ccf6204"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SuiteSparse = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
MathOptInterface = "~0.9"
julia = "^1.4"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GSL = "92c85e6c-cbff-5e0c-80f7-495c94daaecd"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
PolyJuMP = "ddf597a6-d67e-5340-b84c-e37d84115374"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SumOfSquares = "4b9e565b-77fc-50a5-a571-1244f986bda1"

[targets]
test = ["CSV", "DataFrames", "DataStructures", "ForwardDiff", "GSL", "JuMP", "PolyJuMP", "Random", "SumOfSquares"]
